### ISSUE TITLE
Dont work on Atom 1.15 x64

### ISSUE THREAD

**Issue by ASudri** [mikesprague/atom-regex-railroad-diagrams-fork#1]
Hello! Regex-railroad-diagram-fork dont work on Atom 1.15 x64 fo me. When you allocate a regular expression, then nothing happens. Tested in the .js file

**Comment by mikesprague** [comment]
If you can provide more details I can try to look into this but just saying it doesn't work isn't very helpful.

Did you open the developer console and see if there was an error message and if it was related to this package or something else you have installed?

Was the regular expression "loose" in the page or in use in some valid code?

Myself, and several other users, have successfully used this on the build of Atom you mentioned. I have attached a screenshot I just took showing it working in that exact build of Atom. 

![screen shot 2017-04-07 at 8 54 23 am](https://cloud.githubusercontent.com/assets/560705/24800866/eeae1692-1b6f-11e7-9215-15484fbc82c5.png)

If are able to provide more details, including steps to replicate the error/bug, we can reopen this and I'll look into it. Thanks!

**Comment by mikesprague** [comment]
@ASudri One more thought on this... Open your command palette (`ctrl`+`shift`+`p`) and start typing the word railroad. You should see one option like in the screenshot below. 

![railroad-enable](https://cloud.githubusercontent.com/assets/560705/24830210/3b7a3f0c-1c4f-11e7-8bd6-b12e1f2ff0ae.png)

If it says Enable instead of Disable then select it to turn the package on. That's the only other reason I could this not working for you without any further details.

**Comment by ASudri** [comment]
Hello! I just started learning js, so it was difficult for me to grasp in debugging. Thank you, I took your last advice, it worked!
